sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t hieu.trinh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hieu.trinh/docker-react npm run test
